export const GlobalStyles = {
    navbarLink:{
        color:"white",
        textDecoration:"none",
        display:"flex",
        alignItems:"center"
    },
    form:{
        marginTop:40,
        display:"flex",
        justifyContent:"center"
    },
    cartspan:{
        fontSize:"8px",
        backgroundColor:"red",
        borderRadius:"50px",
        width:"15px",
        height:"15px",
        position:"absolute",
        top:"4px",
        left:"30px"
    }
};